# Generated by Django 4.1.4 on 2023-01-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_of_measurement', models.TextField()),
                ('observation_type', models.CharField(max_length=255)),
                ('properties', models.TextField(null=True)),
                ('observed_area', models.TextField(null=True)),
                ('phenomenon_time', models.DateTimeField(null=True)),
                ('result_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('feature', models.TextField()),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('description', models.TextField()),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('sensor_metadata', models.TextField(null=True)),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('result_time', models.DateTimeField()),
                ('result_quality', models.CharField(max_length=255, null=True)),
                ('valid_time', models.DateTimeField(null=True)),
                ('properties', models.TextField(null=True)),
                ('data_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.datastream')),
                ('feature_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.featureofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('properties', models.TextField(null=True)),
                ('things', models.ManyToManyField(to='sensorthings.thing')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorthings.location')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.thing')),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.observedproperty'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.sensor'),
        ),
    ]
