# Generated by Django 4.1.4 on 2023-01-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='sensorthings.thing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_locations', to='sensorthings.thing'),
        ),
        migrations.AlterField(
            model_name='location',
            name='things',
            field=models.ManyToManyField(related_name='locations', to='sensorthings.thing'),
        ),
    ]
