# Generated by Django 4.1.4 on 2023-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0002_datastream_thing_alter_historicallocation_thing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='location',
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='locations',
            field=models.ManyToManyField(related_name='historical_locations', to='sensorthings.location'),
        ),
    ]
