# Generated by Django 4.1.4 on 2023-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='string', max_length=255),
            preserve_default=False,
        ),
    ]
