# Generated by Django 4.1.4 on 2023-01-20 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0004_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='data_stream',
            new_name='datastream',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='properties',
            new_name='parameters',
        ),
        migrations.AddField(
            model_name='observation',
            name='phenomenon_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
