# Generated by Django 4.1.5 on 2023-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0007_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
