# Generated by Django 4.1.5 on 2023-02-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0008_alter_thing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='things',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='elevation',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='thing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='sensorthings.thing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
