# Generated by Django 4.1.5 on 2023-02-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_datastream_featureofinterest_observedproperty_sensor_and_more'),
        ('sensorthings', '0009_remove_location_location_remove_location_things_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='thing',
        ),
        migrations.RemoveField(
            model_name='location',
            name='thing',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='datastream',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='feature_of_interest',
        ),
        migrations.DeleteModel(
            name='DataStream',
        ),
        migrations.DeleteModel(
            name='FeatureOfInterest',
        ),
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='ObservedProperty',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
