# Generated by Django 5.2a1 on 2025-02-07 20:56

import django.db.models.deletion
import iam.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0007_rename_private_workspace_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('elevation_datum', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sampling_feature_type', models.CharField(max_length=200)),
                ('sampling_feature_code', models.CharField(max_length=200)),
                ('site_type', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('data_disclaimer', models.TextField(blank=True, null=True)),
                ('locations', models.ManyToManyField(related_name='things', to='sta.location')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='iam.workspace')),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sta.thing')),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(storage={'BACKEND': 'django.core.files.storage.FileSystemStorage', 'OPTIONS': {'location': 'media'}}, upload_to='photos')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sta.thing')),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
    ]
