# Generated by Django 5.2a1 on 2025-02-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_rename_private_workspace_is_private'),
        ('sta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='workspace',
            field=models.ForeignKey(default='6e0deaf2-a92b-421b-9ece-86783265596f', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='iam.workspace'),
            preserve_default=False,
        ),
    ]
