# Generated by Django 5.2b1 on 2025-03-13 00:11

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "sta/fixtures/default_processing_levels.json")
    call_command("loaddata", "sta/fixtures/default_units.json")


class Migration(migrations.Migration):
    dependencies = [
        ("sta", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
