# Generated by Django 5.2b1 on 2025-04-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0001_initial"),
        ("sta", "0002_datastreamaggregation_datastreamstatus_methodtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datastream",
            name="data_archives",
            field=models.ManyToManyField(
                related_name="datastreams", to="etl.dataarchive"
            ),
        ),
        migrations.AddField(
            model_name="datastream",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="datastreams",
                to="etl.datasource",
            ),
        ),
    ]
