# Generated by Django 5.2.5 on 2025-10-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0003_observation_result_qualifiers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='FileAttachment',
        ),
        migrations.RenameField(
            model_name='fileattachment',
            old_name='photo',
            new_name='file_attachment',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_attachment_type',
            field=models.CharField(default='Photo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_attachments',
                                    to='sta.thing'),
        ),
    ]
