# Generated by Django 5.2.5 on 2025-10-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0003_observation_result_qualifiers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state',
            new_name='admin_area_1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='county',
            new_name='admin_area_2',
        ),
    ]
