# Generated by Django 5.2b1 on 2025-04-15 21:50

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0003_datastream_data_archives_datastream_data_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="observation",
            name="unique_datastream_timestamps",
        ),
        migrations.AlterField(
            model_name="datastream",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="id",
            field=models.UUIDField(default=uuid6.uuid7, editable=False),
        ),
        migrations.AlterField(
            model_name="observation",
            name="pk",
            field=models.CompositePrimaryKey(
                "datastream_id",
                "phenomenon_time",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="observedproperty",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="processinglevel",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="resultqualifier",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="thing",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["id"], name="sta_observa_id_5779e2_idx"),
        ),
    ]
