# Generated by Django 5.2a1 on 2025-02-11 22:02

import django.db.models.deletion
import iam.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0003_observedproperty_processinglevel_resultqualifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('observation_type', models.CharField(max_length=255)),
                ('result_type', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('observed_area', models.CharField(blank=True, max_length=255, null=True)),
                ('sampled_medium', models.CharField(max_length=255)),
                ('value_count', models.IntegerField(blank=True, null=True)),
                ('no_data_value', models.FloatField()),
                ('intended_time_spacing', models.FloatField(blank=True, null=True)),
                ('intended_time_spacing_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregation_statistic', models.CharField(max_length=255)),
                ('time_aggregation_interval', models.FloatField()),
                ('time_aggregation_interval_unit', models.CharField(max_length=255)),
                ('phenomenon_begin_time', models.DateTimeField(blank=True, null=True)),
                ('phenomenon_end_time', models.DateTimeField(blank=True, null=True)),
                ('result_end_time', models.DateTimeField(blank=True, null=True)),
                ('result_begin_time', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('observed_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.observedproperty')),
                ('processing_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.processinglevel')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.sensor')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='sta.thing')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.unit')),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
    ]
