# Generated by Django 5.2a1 on 2025-02-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_alter_collaborator_role_alter_collaborator_user_and_more'),
        ('sta', '0004_datastream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datastreams', to='sta.observedproperty'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datastreams', to='sta.processinglevel'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datastreams', to='sta.sensor'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datastreams', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datastreams', to='sta.unit'),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observed_properties', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processing_levels', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='resultqualifier',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_qualifiers', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensors', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='things', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='units', to='iam.workspace'),
        ),
    ]
