# Generated by Django 5.2a1 on 2025-02-12 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0005_alter_datastream_observed_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='thing',
            field=models.ForeignKey(default='76dadda5-224b-4e1f-8570-e385bd482b2d', on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='sta.thing'),
            preserve_default=False,
        ),
    ]
