# Generated by Django 5.2a1 on 2025-02-12 20:07

import django.db.models.deletion
import iam.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0006_remove_location_workspace_remove_thing_locations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'phenomenon_time', 'id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phenomenon_time', models.DateTimeField()),
                ('result', models.FloatField()),
                ('result_time', models.DateTimeField(blank=True, null=True)),
                ('quality_code', models.CharField(blank=True, max_length=255, null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sta.datastream')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('datastream_id', 'phenomenon_time'), name='unique_datastream_timestamps')],
            },
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
    ]
