# Generated by Django 5.2a1 on 2025-02-12 20:07

from django.db import migrations
from django.conf import settings


def create_timescaledb_extension(apps, schema_editor):
    if getattr(settings, "TIMESCALEDB_ENABLED", False):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")  # noqa
            partition_interval = getattr(settings, "TIMESCALEDB_PARTITION_INTERVAL", "1 day")
            cursor.execute(
                f"SELECT create_hypertable("
                f"'\"sta_observation\"', "
                f"'phenomenon_time', "
                f"chunk_time_interval => INTERVAL '{partition_interval}', "
                f"if_not_exists => TRUE"
                f");"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0007_observation"),
    ]

    operations = [
        migrations.RunPython(create_timescaledb_extension),
    ]
