# Generated by Django 5.2b1 on 2025-02-20 20:02

import sta.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0008_setup_timescaledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to=sta.models.photo.photo_storage_path),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('thing', 'name')},
        ),
    ]
