name: his

channels:
  - conda-forge

dependencies:
  - python=3.10
  - celery=5.2.7
  - django=4.1
  - django-ninja=0.19.1
  - dj-database-url=1.3.0
  - python-decouple=3.7
  - pyyaml=6.0
  - inflection=0.5.1
  - sqlalchemy=1.4.45
  - djangorestframework=3.14
  - django-cors-headers==3.14

  - pip:
      - django-hydrothings==0.1.5
      - hydroloader==0.1.9
      - django-vite==2.0.2
      - sqlalchemy-json==0.5.0
      - geojson-pydantic==0.5.0
      - djangorestframework-simplejwt==4.4.0
      - boto3==1.28.8
