name: his

channels:
  - conda-forge

dependencies:
  - python=3.10
  - celery=5.2.7
  - django=4.1
  - django-ninja=0.19.1
  - dj-database-url=0.5.0
  - python-decouple=3.7
  - pyyaml=6.0
  - inflection=0.5.1
  - sqlalchemy=1.4.45

  - pip:
      - django-hydrothings==0.1.3
      - sqlalchemy-json==0.5.0
      - geojson-pydantic==0.5.0
