name: his

channels:
  - conda-forge

dependencies:
  - python=3.8
  - celery=5.2.7
  - django=4.1
  - django-ninja=0.19.1
  - dj-database-url=1.3.0
  - python-decouple=3.7
  - pyyaml=6.0
  - inflection=0.5.1
  - sqlalchemy=1.4.45
  - django-cors-headers==3.14

  - pip:
      - Authlib==1.2.1
      - hydroserver-sensorthings==0.2.4
      - django-ninja-jwt==5.2.5
      - hydroloader==0.1.15
      - sqlalchemy-json==0.5.0
      - geojson-pydantic==0.5.0
      - boto3==1.28.8
      - django-ses==3.5.0
      - django-storages==1.14.2
      - django_ses==2.5.0
      - djangorestframework-simplejwt==5.3.0
      - django-simple-history==3.4.0
