from .datastreams.schemas import *
from .featuresofinterest.schemas import *
from .historicallocations.schemas import *
from .locations.schemas import *
from .observations.schemas import *
from .observedproperties.schemas import *
from .root.schemas import *
from .sensors.schemas import *
from .things.schemas import *
