# Generated by Django 4.2.4 on 2023-08-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datastream',
            table='Datastream',
        ),
        migrations.AlterModelTable(
            name='featureofinterest',
            table='FeatureOfInterest',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='Observation',
        ),
        migrations.AlterModelTable(
            name='observedproperty',
            table='ObservedProperty',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='Photo',
        ),
        migrations.AlterModelTable(
            name='processinglevel',
            table='ProcessingLevel',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='Sensor',
        ),
        migrations.AlterModelTable(
            name='thing',
            table='Thing',
        ),
        migrations.AlterModelTable(
            name='thingassociation',
            table='ThingAssociation',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='Unit',
        ),
    ]
