# Generated by Django 4.1 on 2023-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='include_data_disclaimer',
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='sampling_feature_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sampling_feature_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='thing',
            name='site_type',
            field=models.CharField(max_length=200),
        ),
    ]
