# Generated by Django 4.2.4 on 2023-09-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultQualifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('person', models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_qualifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResultQualifier',
            },
        ),
    ]
