# Generated by Django 4.2.4 on 2023-09-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_qualifierassociation_resultqualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultqualifier',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_qualifiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
