# Generated by Django 4.1 on 2023-08-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='photo',
            name='file_path',
            field=models.CharField(default='/', max_length=1000),
            preserve_default=False,
        ),
    ]
