# Generated by Django 4.1 on 2023-08-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_url_photo_link_photo_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
