# Generated by Django 4.1 on 2023-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unitchangelog_thingchangelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='is_data_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datastreamchangelog',
            name='is_data_visible',
            field=models.BooleanField(default=True),
        ),
    ]
