# Generated by Django 4.1 on 2023-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_thing_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='model_url',
            new_name='model_link',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='encoding_type',
            field=models.CharField(default='application/json', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='method_type',
            field=models.CharField(default='Instrument Deployment', max_length=100),
            preserve_default=False,
        ),
    ]
