# Generated by Django 4.1 on 2023-12-04 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datastream_is_data_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('thing', models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
            options={
                'db_table': 'Tag',
                'unique_together': {('thing', 'key', 'value')},
            },
        ),
    ]
