# Generated by Django 4.1 on 2023-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_model_url_sensor_model_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinglevel',
            old_name='processing_level_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
