# Generated by Django 4.1 on 2023-12-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.thing'),
        ),
    ]
