# Generated by Django 4.1 on 2023-09-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_processing_level_code_processinglevel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_type',
            new_name='type',
        ),
    ]
