# Generated by Django 4.2.4 on 2023-12-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_thing_hydroshare_archive_link_and_more'),
        ('core', '0006_alter_tag_thing'),
    ]

    operations = [
    ]
