# Generated by Django 4.1 on 2023-12-21 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20231209_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataloader',
            name='person',
            field=models.ForeignKey(db_column='personId', on_delete=django.db.models.deletion.CASCADE, related_name='data_loaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataloaderchangelog',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_loader',
            field=models.ForeignKey(blank=True, db_column='dataLoaderId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dataloader'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source_thru',
            field=models.DateTimeField(blank=True, db_column='dataSourceThru', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_start_row',
            field=models.PositiveIntegerField(blank=True, db_column='dataStartRow', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='end_time',
            field=models.DateTimeField(blank=True, db_column='endTime', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='header_row',
            field=models.PositiveIntegerField(blank=True, db_column='headerRow', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='interval_units',
            field=models.CharField(blank=True, db_column='intervalUnits', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='last_sync_message',
            field=models.TextField(blank=True, db_column='lastSyncMessage', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='last_sync_successful',
            field=models.BooleanField(blank=True, db_column='lastSyncSuccessful', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='last_synced',
            field=models.DateTimeField(blank=True, db_column='lastSynced', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='next_sync',
            field=models.DateTimeField(blank=True, db_column='nextSync', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='person',
            field=models.ForeignKey(db_column='personId', on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='quote_char',
            field=models.CharField(blank=True, db_column='quoteChar', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='start_time',
            field=models.DateTimeField(blank=True, db_column='startTime', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='timestamp_column',
            field=models.CharField(blank=True, db_column='timestampColumn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='timestamp_format',
            field=models.CharField(blank=True, db_column='timestampFormat', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='timestamp_offset',
            field=models.CharField(blank=True, db_column='timestampOffset', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='data_loader',
            field=models.ForeignKey(blank=True, db_column='dataLoaderId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataloader'),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='data_source_thru',
            field=models.DateTimeField(blank=True, db_column='dataSourceThru', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='data_start_row',
            field=models.PositiveIntegerField(blank=True, db_column='dataStartRow', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='end_time',
            field=models.DateTimeField(blank=True, db_column='endTime', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='header_row',
            field=models.PositiveIntegerField(blank=True, db_column='headerRow', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='interval_units',
            field=models.CharField(blank=True, db_column='intervalUnits', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='last_sync_message',
            field=models.TextField(blank=True, db_column='lastSyncMessage', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='last_sync_successful',
            field=models.BooleanField(blank=True, db_column='lastSyncSuccessful', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='last_synced',
            field=models.DateTimeField(blank=True, db_column='lastSynced', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='next_sync',
            field=models.DateTimeField(blank=True, db_column='nextSync', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='quote_char',
            field=models.CharField(blank=True, db_column='quoteChar', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='start_time',
            field=models.DateTimeField(blank=True, db_column='startTime', null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='timestamp_column',
            field=models.CharField(blank=True, db_column='timestampColumn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='timestamp_format',
            field=models.CharField(blank=True, db_column='timestampFormat', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcechangelog',
            name='timestamp_offset',
            field=models.CharField(blank=True, db_column='timestampOffset', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='data_source',
            field=models.ForeignKey(blank=True, db_column='dataSourceId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasource'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='data_source_column',
            field=models.CharField(blank=True, db_column='dataSourceColumn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing',
            field=models.FloatField(blank=True, db_column='intendedTimeSpacing', null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='is_data_visible',
            field=models.BooleanField(db_column='isDataVisible', default=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='is_visible',
            field=models.BooleanField(db_column='isVisible', default=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='observed_area',
            field=models.CharField(blank=True, db_column='observedArea', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='data_source',
            field=models.ForeignKey(blank=True, db_column='dataSourceId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.datasource'),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='data_source_column',
            field=models.CharField(blank=True, db_column='dataSourceColumn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='intended_time_spacing',
            field=models.FloatField(blank=True, db_column='intendedTimeSpacing', null=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='is_data_visible',
            field=models.BooleanField(db_column='isDataVisible', default=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='is_visible',
            field=models.BooleanField(db_column='isVisible', default=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='observed_area',
            field=models.CharField(blank=True, db_column='observedArea', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='dataloader',
            table='DataLoader',
        ),
        migrations.AlterModelTable(
            name='datasource',
            table='DataSource',
        ),
    ]
