# Generated by Django 4.1 on 2023-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_unit_type_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observedproperty',
            name='variable_code',
        ),
        migrations.RemoveField(
            model_name='observedproperty',
            name='variable_type',
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='code',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='type',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
