# Generated by Django 4.2.4 on 2023-09-01 17:24

from django.db import migrations, models
from uuid import uuid4
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_unit_type_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='phenomenon_start_time',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='result_begin_time',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='result_end_time',
        ),
        migrations.AddField(
            model_name='datastream',
            name='phenomenon_begin_time',
            field=models.DateTimeField(blank=True, db_column='phenomenonBeginTime', null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='aggregation_statistic',
            field=models.CharField(db_column='aggregationStatistic', default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing_units',
            field=models.ForeignKey(blank=True, db_column='intendedTimeSpacingUnitsId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_time_spacing_units', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='name',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='no_data_value',
            field=models.FloatField(db_column='noDataValue', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='observation_type',
            field=models.CharField(db_column='observationType', default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(db_column='observedPropertyId', on_delete=django.db.models.deletion.PROTECT, to='core.observedproperty'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='phenomenon_end_time',
            field=models.DateTimeField(blank=True, db_column='phenomenonEndTime', null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(db_column='processingLevelId', default=uuid4(), on_delete=django.db.models.deletion.PROTECT, to='core.processinglevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='result_type',
            field=models.CharField(db_column='resultType', default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sampled_medium',
            field=models.CharField(db_column='sampledMedium', default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(db_column='sensorId', on_delete=django.db.models.deletion.PROTECT, to='core.sensor'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, to='core.thing'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='time_aggregation_interval',
            field=models.FloatField(db_column='timeAggregationInterval', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='time_aggregation_interval_units',
            field=models.ForeignKey(db_column='timeAggregationIntervalUnitsId', default=uuid4(), on_delete=django.db.models.deletion.PROTECT, related_name='time_aggregation_interval_units', to='core.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(db_column='unitId', default=uuid4(), on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastream',
            name='value_count',
            field=models.IntegerField(blank=True, db_column='valueCount', null=True),
        ),
        migrations.AlterField(
            model_name='featureofinterest',
            name='encoding_type',
            field=models.CharField(db_column='encodingType', max_length=255),
        ),
    ]
