# Generated by Django 4.2.4 on 2023-09-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_datastream_phenomenon_start_time_and_more'),
        ('core', '0008_remove_observedproperty_variable_code_and_more'),
    ]

    operations = [
    ]
