# Generated by Django 4.1 on 2023-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dataloader_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing_units',
            field=models.CharField(blank=True, db_column='intendedTimeSpacingUnits', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='intended_time_spacing_units',
            field=models.CharField(blank=True, db_column='intendedTimeSpacingUnits', max_length=255, null=True),
        ),
    ]
