# Generated by Django 4.2.4 on 2023-09-01 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_merge_20230901_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='location',
            field=models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, to='core.thing'),
        ),
        migrations.AlterField(
            model_name='location',
            name='elevation_datum',
            field=models.CharField(blank=True, db_column='elevationDatum', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='encoding_type',
            field=models.CharField(db_column='encodingType', max_length=255),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.CharField(db_column='filePath', max_length=1000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.thing'),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='encoding_type',
            field=models.CharField(db_column='encodingType', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='method_code',
            field=models.CharField(blank=True, db_column='methodCode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='method_link',
            field=models.CharField(blank=True, db_column='methodLink', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='method_type',
            field=models.CharField(db_column='methodType', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='model_link',
            field=models.CharField(blank=True, db_column='modelLink', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thing',
            name='data_disclaimer',
            field=models.TextField(blank=True, db_column='dataDisclaimer', null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='is_private',
            field=models.BooleanField(db_column='isPrivate', default=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.OneToOneField(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='thing', to='core.location'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sampling_feature_code',
            field=models.CharField(db_column='samplingFeatureCode', max_length=200),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sampling_feature_type',
            field=models.CharField(db_column='samplingFeatureType', max_length=200),
        ),
        migrations.AlterField(
            model_name='thing',
            name='site_type',
            field=models.CharField(db_column='siteType', max_length=200),
        ),
        migrations.AlterField(
            model_name='thingassociation',
            name='follows_thing',
            field=models.BooleanField(db_column='followsThing', default=False),
        ),
        migrations.AlterField(
            model_name='thingassociation',
            name='is_primary_owner',
            field=models.BooleanField(db_column='isPrimaryOwner', default=False),
        ),
        migrations.AlterField(
            model_name='thingassociation',
            name='owns_thing',
            field=models.BooleanField(db_column='ownsThing', default=False),
        ),
        migrations.AlterField(
            model_name='thingassociation',
            name='person',
            field=models.ForeignKey(db_column='personId', on_delete=django.db.models.deletion.CASCADE, related_name='thing_associations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thingassociation',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='core.thing'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='person',
            field=models.ForeignKey(blank=True, db_column='personId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
