# Generated by Django 4.1 on 2024-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_datastream_intended_time_spacing_units_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='locationchangelog',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
