# Generated by Django 4.1 on 2023-09-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_historicallocation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(db_column='observedPropertyId', on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='core.observedproperty'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(db_column='processingLevelId', on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='core.processinglevel'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(db_column='sensorId', on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='core.sensor'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='core.thing'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='core.unit'),
        ),
    ]
