# Generated by Django 4.2 on 2024-03-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_location_country_locationchangelog_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('thing', 'key')},
        ),
    ]
