# Generated by Django 4.1 on 2024-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_location_country_locationchangelog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='use_default_description',
            field=models.BooleanField(db_column='useDefaultDescription', default=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='use_default_name',
            field=models.BooleanField(db_column='useDefaultName', default=True),
        ),
        migrations.AddField(
            model_name='datastreamchangelog',
            name='use_default_description',
            field=models.BooleanField(db_column='useDefaultDescription', default=True),
        ),
        migrations.AddField(
            model_name='datastreamchangelog',
            name='use_default_name',
            field=models.BooleanField(db_column='useDefaultName', default=True),
        ),
    ]
