# Generated by Django 4.1 on 2023-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_datastream_observed_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='observed_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='result_begin_time',
            field=models.DateTimeField(blank=True, db_column='resultBeginTime', null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='result_time',
            field=models.DateTimeField(blank=True, db_column='resultTime', null=True),
        ),
    ]
