# Generated by Django 4.1 on 2024-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_datastream_use_default_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
