# Generated by Django 4.2 on 2024-03-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_datastream_name_alter_datastreamchangelog_name'),
        ('core', '0012_alter_tag_unique_together'),
    ]

    operations = [
    ]
