# Generated by Django 4.1 on 2024-01-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_datastream_name_alter_datastreamchangelog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='use_default_description',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='use_default_name',
        ),
        migrations.RemoveField(
            model_name='datastreamchangelog',
            name='use_default_description',
        ),
        migrations.RemoveField(
            model_name='datastreamchangelog',
            name='use_default_name',
        ),
    ]
