# Generated by Django 4.2 on 2024-04-18 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20240320_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('thing', models.OneToOneField(db_column='thingId', on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='core.thing')),
            ],
            options={
                'db_table': 'Archive',
            },
        ),
    ]
