# Generated by Django 4.2 on 2024-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_archive_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='hydroshare_archive_resource_id',
        ),
        migrations.RemoveField(
            model_name='thingchangelog',
            name='hydroshare_archive_resource_id',
        ),
    ]
