# Generated by Django 4.2 on 2024-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_thing_hydroshare_archive_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datastreamchangelog',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
