# Generated by Django 4.2 on 2024-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_archive_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='hydroshare_archive_resource_id',
        ),
        migrations.RemoveField(
            model_name='thingchangelog',
            name='hydroshare_archive_resource_id',
        ),
        migrations.AddField(
            model_name='datastream',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datastreamchangelog',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
