# Generated by Django 4.2 on 2024-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_thing_hydroshare_archive_resource_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='time_aggregation_interval_units',
            field=models.CharField(db_column='timeAggregationIntervalUnits', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastreamchangelog',
            name='time_aggregation_interval_units',
            field=models.CharField(db_column='timeAggregationIntervalUnits', default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
