# Generated by Django 4.2 on 2024-06-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_update_datastream_time_aggregation_interval_units_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='datasourcechangelog',
            old_name='url',
            new_name='link',
        ),
    ]
