# Generated by Django 4.2 on 2024-06-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_url_datasource_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingassociation',
            name='follows_thing',
        ),
        migrations.RemoveField(
            model_name='thingassociationchangelog',
            name='follows_thing',
        ),
    ]
