# Generated by Django 5.0.6 on 2025-01-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_thingassociation_follows_thing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.FileField(db_column='filePath', storage={'BACKEND': 'django.core.files.storage.FileSystemStorage', 'OPTIONS': {'location': 'media'}}, upload_to='photos'),
        ),
    ]
