# Generated by Django 5.2b1 on 2025-04-10 16:24

import django.db.models.deletion
import iam.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("orchestration_system_type", models.CharField(max_length=255)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orchestration_systems",
                        to="iam.workspace",
                    ),
                ),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interval_units",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("crontab", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("paused", models.BooleanField(default=False)),
                ("last_run_successful", models.BooleanField(blank=True, null=True)),
                ("last_run_message", models.TextField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="data_sources",
                        to="iam.workspace",
                    ),
                ),
                (
                    "orchestration_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="data_sources",
                        to="etl.orchestrationsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="DataArchive",
            fields=[
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interval_units",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("crontab", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("paused", models.BooleanField(default=False)),
                ("last_run_successful", models.BooleanField(blank=True, null=True)),
                ("last_run_message", models.TextField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="data_archives",
                        to="iam.workspace",
                    ),
                ),
                (
                    "orchestration_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="data_archives",
                        to="etl.orchestrationsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
    ]
