# Generated by Django 5.2b1 on 2025-03-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasource",
            old_name="etl_configuration_settings",
            new_name="extractor_configuration_settings",
        ),
        migrations.RenameField(
            model_name="linkeddatastream",
            old_name="etl_configuration_settings",
            new_name="extractor_configuration_settings",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="etl_configuration",
        ),
        migrations.RemoveField(
            model_name="linkeddatastream",
            name="etl_configuration",
        ),
        migrations.AddField(
            model_name="datasource",
            name="extractor_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_source_extractor_set",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="loader_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_source_loader_set",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="loader_configuration_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasource",
            name="transformer_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_source_transformer_set",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="transformer_configuration_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etlconfiguration",
            name="etl_configuration_model",
            field=models.CharField(default="datasource", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkeddatastream",
            name="extractor_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="linked_datastreams_extractor",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="linkeddatastream",
            name="loader_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="linked_datastreams_loader",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="linkeddatastream",
            name="loader_configuration_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linkeddatastream",
            name="transformer_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="linked_datastreams_transformer",
                to="etl.etlconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="linkeddatastream",
            name="transformer_configuration_settings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
