# Generated by Django 5.2.5 on 2025-11-25 16:26

import django.db.models.deletion
import iam.models.utils
import uuid6
from django.db import migrations, models


# def update_settings_fields(apps, schema_editor):
#     DataSource = apps.get_model("etl", "DataSource")
#     Payload = apps.get_model("etl", "Payload")
#     PayloadMapping = apps.get_model("etl", "PayloadMapping")
#     PayloadMappingPath = apps.get_model("etl", "PayloadMappingPath")
#     PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
#     CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
#     IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
#
#     for data_source in DataSource.objects.all():
#         settings = data_source.settings or {}
#
#         data_source.data_source_type = settings.get("type", "ETL")
#         data_source.extractor_type = settings.get("extractor", {}).get("type")
#         data_source.extractor_settings = {
#             k: v for k, v in settings.get("extractor", {}).items() if k != "type"
#         }
#         data_source.transformer_type = settings.get("transformer", {}).get("type")
#         data_source.transformer_settings = {
#             k: v for k, v in settings.get("transformer", {}).items() if k != "type"
#         }
#         data_source.loader_type = settings.get("loader", {}).get("type")
#         data_source.loader_settings = {
#             k: v for k, v in settings.get("loader", {}).items() if k != "type"
#         }
#
#         if data_source.interval or data_source.crontab:
#             periodic_task = PeriodicTask.objects.create(
#                 name=str(data_source.id),
#                 task="etl.tasks.process_data_source",
#                 kwargs={"data_source_id": str(data_source.id)},
#                 enabled=not data_source.paused,
#                 last_run_at=data_source.last_run,
#                 date_changed=datetime.now(timezone.utc),
#                 start_time=data_source.start_time,
#             )
#
#             if data_source.interval:
#                 interval_schedule = IntervalSchedule.objects.create(
#                     every=data_source.interval,
#                     period=data_source.interval_units,
#                 )
#                 periodic_task.interval = interval_schedule
#
#             elif data_source.crontab:
#                 crontab_split = data_source.crontab.split(" ")
#                 crontab_schedule = CrontabSchedule.objects.create(
#                     minute=crontab_split[0],
#                     hour=crontab_split[1],
#                     day_of_week=crontab_split[2],
#                     day_of_month=crontab_split[3],
#                     month_of_year=crontab_split[4],
#                     timezone="UTC"
#                 )
#                 periodic_task.crontab = crontab_schedule
#
#             periodic_task.save()
#             data_source.schedule = periodic_task
#
#         for payload_setting in settings.get("payloads", []):
#             payload = Payload.objects.create(
#                 id=str(payload_setting.get("id", uuid6.uuid7())),
#                 name=payload_setting["name"],
#                 data_source=data_source,
#                 extractor_variables=payload_setting.get("extractorVariables", {}),
#                 transformer_variables=payload_setting.get("transformerVariables", {}),
#                 loader_variables=payload_setting.get("loaderVariables", {}),
#             )
#
#             for mapping_setting in payload_setting.get("mappings", []):
#                 mapping = PayloadMapping.objects.create(
#                     payload=payload,
#                     source_identifier=mapping_setting["sourceIdentifier"]
#                 )
#
#                 for path_setting in mapping_setting.get("paths", []):
#                     PayloadMappingPath.objects.create(
#                         payload_mapping=mapping,
#                         target_identifier=path_setting["targetIdentifier"],
#                         transformations=path_setting.get("dataTransformations", []),
#                     )
#
#         data_source.save()
#
#
# def reverse_update_settings_fields(apps, schema_editor):
#     raise RuntimeError("This migration is irreversible.")


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("etl", "0002_initial"),
        ("iam", "0003_role_is_apikey_role_role_is_user_role_and_more"),
        ("sta", "0005_remove_datastream_data_archives_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasource",
            name="orchestration_system",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="workspace",
        ),
        migrations.AlterField(
            model_name="orchestrationsystem",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orchestration_systems",
                to="iam.workspace",
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=255)),
                (
                    "extractor_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extractor_settings", models.JSONField(default=dict)),
                (
                    "transformer_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transformer_settings", models.JSONField(default=dict)),
                (
                    "loader_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("loader_settings", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="iam.workspace",
                    ),
                ),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("paused", models.BooleanField(default=False)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("extractor_variables", models.JSONField(default=dict)),
                ("transformer_variables", models.JSONField(default=dict)),
                ("loader_variables", models.JSONField(default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="etl.job",
                    ),
                ),
                (
                    "orchestration_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="etl.orchestrationsystem",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etl_task",
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            bases=(models.Model, iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="TaskMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_identifier", models.CharField(max_length=255)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="etl.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskMappingPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_identifier", models.CharField(max_length=255)),
                ("transformations", models.JSONField(default=dict)),
                (
                    "task_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="etl.taskmapping",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.task"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DataArchive",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
