# Generated by Django 5.2.2 on 2026-01-13 00:03

import django.db.models.deletion
import iam.models.utils
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_remove_datasource_orchestration_system_and_more'),
        ('iam', '0005_alter_permission_resource_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='DataConnection',
        ),
        migrations.RenameField(
            model_name="dataconnection",
            old_name="job_type",
            new_name="data_connection_type",
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connections',
                                    to='iam.workspace'),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='job',
            new_name='data_connection',
        ),
    ]
