# Generated by Django 5.2.2 on 2026-01-14 17:31

import django.db.models.deletion
from django.db import migrations, models


def forwards_set_task_workspace(apps, schema_editor):
    Task = apps.get_model("etl", "Task")

    qs = Task.objects.select_related("data_connection__workspace")

    for task in qs:
        if task.workspace_id is None and task.data_connection_id:
            task.workspace = task.data_connection.workspace
            task.save(update_fields=["workspace"])


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_task_job_dataconnection_task_data_connection_and_more'),
        ('iam', '0005_alter_permission_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='iam.workspace'),
        ),
        migrations.RunPython(
            forwards_set_task_workspace,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="task",
            name="workspace",
            field=models.ForeignKey(null=False, blank=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name="tasks", to="iam.workspace"),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_connections', to='iam.workspace'),
        ),
    ]
