# Generated by Django 5.2.2 on 2026-02-20 21:42

import django.db.models.deletion
import domains.iam.models.utils
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_remove_datasource_orchestration_system_and_more'),
        ('iam', '0004_alter_permission_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnectionNotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connection_notifications', to='iam.collaborator')),
                ('data_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='etl.dataconnection')),
            ],
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
    ]
