# Generated by Django 5.2b1 on 2025-03-01 00:11

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "iam/fixtures/default_roles.json")
    call_command("loaddata", "iam/fixtures/default_types.json")


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
