# Generated by Django 5.0.6 on 2025-02-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_workspace_role_workspacedeleteconfirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('*', 'Full'), ('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=50)),
                ('resource_type', models.CharField(choices=[('*', 'All'), ('APIKey', 'API Key'), ('Role', 'Role'), ('DataSource', 'Data Source'), ('ETLSystem', 'ETL System'), ('Thing', 'Thing'), ('Datastream', 'Datastream'), ('Observation', 'Observation'), ('Sensor', 'Sensor'), ('ObservedProperty', 'Observed Property'), ('ProcessingLevel', 'Processing Level'), ('Unit', 'Unit'), ('ResultQualifier', 'Result Qualifier')], max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='iam.role')),
            ],
        ),
    ]
