# Generated by Django 5.0.6 on 2025-02-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource_type',
            field=models.CharField(choices=[('*', 'All'), ('APIKey', 'API Key'), ('Role', 'Role'), ('Collaborator', 'Collaborator'), ('DataSource', 'Data Source'), ('ETLSystem', 'ETL System'), ('Thing', 'Thing'), ('Datastream', 'Datastream'), ('Observation', 'Observation'), ('Sensor', 'Sensor'), ('ObservedProperty', 'Observed Property'), ('ProcessingLevel', 'Processing Level'), ('Unit', 'Unit'), ('ResultQualifier', 'Result Qualifier')], max_length=50),
        ),
    ]
