# Generated by Django 5.0.6 on 2025-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_permission_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='_organization_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_user_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(default='Other', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Other', max_length=255),
            preserve_default=False,
        ),
    ]
