# Generated by Django 5.0.6 on 2025-02-06 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_remove_organization__organization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacedeleteconfirmation',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delete_confirmation', to='iam.workspace'),
        ),
    ]
