# Generated by Django 5.2a1 on 2025-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_alter_workspacedeleteconfirmation_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='private',
            new_name='is_private',
        ),
    ]
