# Generated by Django 5.2a1 on 2025-02-12 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_rename_private_workspace_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collaborator_assignments', to='iam.role'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workspace_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collaborators', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='iam.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
