# Generated by Django 5.2b1 on 2025-02-27 18:38

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "iam/fixtures/default_roles.json")
    call_command("loaddata", "iam/fixtures/default_types.json")


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0008_alter_collaborator_role_alter_collaborator_user_and_more"),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
