# Generated by Django 4.1.5 on 2023-01-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('port', models.IntegerField(null=True)),
                ('db_name', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('username', models.IntegerField(null=True)),
                ('password', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataStoreDialect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url_pattern', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataStoreInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastores.datastore')),
            ],
        ),
        migrations.CreateModel(
            name='DataStoreSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_store_dialect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastores.datastoredialect')),
                ('data_store_information_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastores.datastoreinformationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='data_store_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastores.datastoreschema'),
        ),
    ]
