# Generated by Django 4.2.3 on 2023-08-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orcid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
