# Generated by Django 4.1 on 2023-09-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_organization_person_person_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.OneToOneField(blank=True, db_column='organizationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='accounts.organization'),
        ),
    ]
