# Generated by Django 4.1.5 on 2023-02-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_organization_user_customuser_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='accounts.Membership', to='accounts.organization'),
        ),
    ]
