# Generated by Django 4.2 on 2024-04-17 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_person_hydroshare_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=64, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField()),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
