# Generated by Django 4.2 on 2024-03-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
