# Generated by Django 4.1.5 on 2023-02-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
