# Generated by Django 5.0.6 on 2024-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='permissions',
            field=models.JSONField(blank=True, db_column='permissions', null=True),
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='permissions',
            new_name='_permissions',
        ),
    ]
