# Generated by Django 4.2 on 2024-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_apikey_enabled_apikey_last_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='scope',
        ),
    ]
