# Generated by Django 4.1.5 on 2023-02-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
