export const siteTypes = [
  'Atmosphere',
  'Borehole',
  'Ditch',
  'Estuary',
  'House',
  'Lake, Reservoir, Impoundment',
  'Land',
  'Laboratory or sample-preparation area',
  'Observation well',
  'Other',
  'Pavement',
  'Soil hole',
  'Spring',
  'Stream',
  'Stream gage',
  'Storm sewer',
  'Tidal stream',
  'Water quality station',
  'Weather station',
  'Wetland',
]

export const userTypes = [
  'University Faculty',
  'University Professional or Research Staff',
  'Post-Doctoral Fellow',
  'University Graduate Student',
  'University Undergraduate Student',
  'Commercial/Professional',
  'Government Official',
  'School Student Kindergarten to 12th Grade',
  'School Teacher Kindergarten to 12th Grade',
  'Organization',
  'Other',
]

export const methodTypes = [
  'Derivation',
  'Estimation',
  'Instrument Deployment',
  'Observation',
  'Simulation',
  'Specimen Analysis',
  'Unknown',
]

export const mediumTypes = [
  'Air',
  'Equipment',
  'Gas',
  'Habitat',
  'Ice',
  'Liquid aqueous',
  'Liquid organic',
  'Mineral',
  'Not applicable',
  'Organism',
  'Other',
  'Particulate',
  'Regolith',
  'Rock',
  'Sediment',
  'Snow',
  'Soil',
  'Tissue',
  'Unknown',
  'Vegetation',
]

export const statusTypes = ['Complete', 'Ongoing', 'Planned', 'Unknown']

export const aggregationTypes = [
  'Average',
  'Best easy systematic estimator',
  'Categorical',
  'Confidence Interval',
  'Constant over interval',
  'Continuous',
  'Cumulative',
  'Incremental',
  'Maximum',
  'Median',
  'Minimum',
  'Mode',
  'Sporadic',
  'Standard deviation',
  'Standard error of mean',
  'Standard error of the mean',
  'Unknown',
  'Variance',
]

export const OPVariableTypes = [
  'Age',
  'Biota',
  'Chemistry',
  'Climate',
  'End-Member',
  'Geology',
  'Hydrology',
  'Instrumentation',
  'Major oxide or element',
  'Model data',
  'Noble gas',
  'Radiogenic isotopes',
  'Rare earth element',
  'Ratio',
  'Rock mode',
  'Soil',
  'Speciation ratio',
  'Stable isotopes',
  'Trace element',
  'Unknown',
  'Uranium series',
  'Volatile',
  'Water quality',
]
