// The purpose of this file is to reduce the network payload size to improve load speed of our app
// This file imports only the mdi icons we need, reducing the mdi payload from ~400kb to ~4kb
export {
  mdiMenuOpen,
  mdiMagnify,
  mdiMenu,
  mdiEmail,
  mdiGithub,
  mdiResistor,
  mdiDatabaseOutline,
  mdiCogOutline,
  mdiLockOpenOutline,
  mdiGoogle,
  mdiAccountEditOutline,
  mdiAccountRemove,
  mdiMenuDown,
  mdiAccountCircle,
  mdiLogout,
  mdiLogin,
  mdiAccountPlusOutline,
  mdiHome,
  mdiLayersSearch,
  mdiMapMarkerMultiple,
  mdiDatabaseCog,
  mdiFileChart,
  mdiFileUpload,
  mdiFileDocument,
  mdiDownloadCircle,
  mdiDelete,
  mdiPlay,
  mdiPause,
  mdiDotsVertical,
  mdiInformation,
  mdiPencil,
  mdiRefresh,
  mdiHelpCircle,
  mdiApple,
  mdiMicrosoftWindows,
  mdiArrowLeft,
  mdiEye,
  mdiEyeOff,
  mdiLinkVariant,
  mdiChartLine,
  mdiHelpCircleOutline,
  mdiPaperclip,
  mdiCloseCircle,
} from '@mdi/js'
