# Generated by Django 4.1.5 on 2023-01-19 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorthings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owns_thing', models.BooleanField(default=False)),
                ('follows_thing', models.BooleanField(default=False)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.thing')),
            ],
        ),
    ]
