# Generated by Django 4.1.5 on 2023-02-22 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensormodel',
            unique_together={('user', 'name', 'manufacturer')},
        ),
    ]
