# Generated by Django 4.2.3 on 2023-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglevel',
            name='new_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='new_id',
            field=models.UUIDField(null=True),
        ),
    ]
