# Generated by Django 4.1.5 on 2023-01-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0007_alter_location_location'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorManufacturer',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.sensormanufacturer')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.sensor')),
            ],
        ),
    ]
