# Generated by Django 4.1.5 on 2023-02-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_sensormodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_model',
        ),
        migrations.AddField(
            model_name='sensor',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SensorModel',
        ),
    ]
