# Generated by Django 4.2.3 on 2023-07-31 22:42

from django.db import migrations, models
from sites.models import Datastream
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_processinglevel_new_id_unit_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglevel',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='intended_time_spacing_units_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_time_spacing_uuid', to='sites.unit', to_field='new_id'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='processing_level_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_level_uuid', to='sites.processinglevel', to_field='new_id'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='time_aggregation_interval_units_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_aggregation_interval_uuid', to='sites.unit', to_field='new_id'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='unit_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_uuid', to='sites.unit', to_field='new_id'),
        ),
    ]
