# Generated by Django 4.1.5 on 2023-02-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_sensormanufacturer_sensormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_of_measurement', models.TextField()),
                ('observation_type', models.CharField(max_length=255)),
                ('properties', models.TextField(null=True)),
                ('observed_area', models.TextField(null=True)),
                ('phenomenon_time', models.DateTimeField(null=True)),
                ('result_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('feature', models.TextField()),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('description', models.TextField()),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('sensor_metadata', models.TextField(null=True)),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('properties', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time', models.DateTimeField()),
                ('result', models.CharField(max_length=255)),
                ('result_time', models.DateTimeField()),
                ('result_quality', models.CharField(max_length=255, null=True)),
                ('valid_time', models.DateTimeField(null=True)),
                ('parameters', models.TextField(null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.datastream')),
                ('feature_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.featureofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('encoding_type', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='sites.thing')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('locations', models.ManyToManyField(related_name='historical_locations', to='sites.location')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_locations', to='sites.thing')),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.observedproperty'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.sensor'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='sites.thing'),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.sensor'),
        ),
        migrations.AlterField(
            model_name='thingownership',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.thing'),
        ),
    ]
