# Generated by Django 4.1.5 on 2023-02-24 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_sensor_method_type_remove_sensor_sensor_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='id'
        ),
        migrations.AddField(
            model_name='thing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
        ),
    ]
