# Generated by Django 4.1.5 on 2023-02-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_sensor_method_type_remove_sensor_sensor_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='method_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
