# Generated by Django 4.2.3 on 2023-07-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_datastream_intended_time_spacing_units_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='intended_time_spacing_units',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='processing_level',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='unit',
        ),
    ]
