# Generated by Django 4.1.4 on 2023-01-17 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sensorthings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0003_remove_site_registration_date_delete_thingownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorthings.thing')),
            ],
        ),
    ]
