# Generated by Django 4.1.5 on 2023-02-10 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_datastream_featureofinterest_observedproperty_sensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='id'
        ),
        migrations.AddField(
            model_name='thing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
        ),
    ]
