# Generated by Django 4.1.5 on 2023-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_sensor_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
