# Generated by Django 4.2.3 on 2023-07-31 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_datastream_intended_time_spacing_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing_units_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_time_spacing_uuid', to='sites.unit', to_field='new_id'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_level_uuid', to='sites.processinglevel', to_field='new_id'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='time_aggregation_interval_units_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_aggregation_interval_uuid', to='sites.unit', to_field='new_id'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_uuid', to='sites.unit', to_field='new_id'),
        ),
    ]
