# Generated by Django 4.1.5 on 2023-02-10 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0004_alter_thing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owns_thing', models.BooleanField(default=False)),
                ('follows_thing', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_associations', to=settings.AUTH_USER_MODEL)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='sites.thing')),
            ],
            options={
                'unique_together': {('thing', 'person')},
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='id'
        ),
        migrations.AddField(
            model_name='sensor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
        ),
        migrations.DeleteModel(
            name='ThingOwnership',
        ),
    ]
