# Generated by Django 4.1.4 on 2023-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_thingownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingownership',
            name='follows_thing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='thingownership',
            name='owns_thing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
