# Generated by Django 4.1.5 on 2023-02-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_thingassociation_alter_sensor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='sites.sensor'),
        ),
    ]
