# Generated by Django 4.2.3 on 2023-07-31 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_datastream_intended_time_spacing_units_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='processing_level_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_level_uuid', to='sites.processinglevel'),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
