# Generated by Django 4.1.5 on 2023-02-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_sensor_name_alter_sensormodel_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedproperty',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
