# Generated by Django 4.1.5 on 2023-02-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_observedproperty_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('unit_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.unit'),
        ),
    ]
