# Generated by Django 4.1.5 on 2023-02-14 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_observedproperty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='sites.sensor'),
        ),
    ]
