# Generated by Django 4.1.5 on 2023-02-28 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0007_unit_datastream_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='observed_area',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='phenomenon_time',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='result_time',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='datastream',
            name='aggregation_statistic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='intended_time_spacing',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='intended_time_spacing_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_time_spacing', to='sites.unit'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='no_data_value',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='phenomenon_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='phenomenon_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='result_begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='result_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='result_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='sampled_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='time_aggregation_interval',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastream',
            name='time_aggregation_interval_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_aggregation_interval', to='sites.unit'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='value_count',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='observation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProcessingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_level_code', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('explanation', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.processinglevel'),
        ),
    ]
