# Generated by Django 4.2.3 on 2023-07-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_datastream_intended_time_spacing_units_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastream',
            old_name='intended_time_spacing_units_uuid',
            new_name='intended_time_spacing_units',
        ),
        migrations.RenameField(
            model_name='datastream',
            old_name='processing_level_uuid',
            new_name='processing_level',
        ),
        migrations.RenameField(
            model_name='datastream',
            old_name='time_aggregation_interval_units_uuid',
            new_name='time_aggregation_interval_units',
        ),
        migrations.RenameField(
            model_name='datastream',
            old_name='unit_uuid',
            new_name='unit',
        ),
    ]
