# Generated by Django 4.2.3 on 2023-07-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_rename_intended_time_spacing_units_uuid_datastream_intended_time_spacing_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='intended_time_spacing_units',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_time_spacing', to='sites.unit'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_level', to='sites.processinglevel'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='time_aggregation_interval_units',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_aggregation_interval', to='sites.unit'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='sites.unit'),
        ),
    ]
