# Generated by Django 4.1.5 on 2023-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_datastream_observed_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='value_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
