# Generated by Django 4.1.5 on 2023-02-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_observation_result_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='feature_of_interest',
        ),
    ]
