# Generated by Django 4.1.5 on 2023-03-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_unit_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureofinterest',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='location',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='observedproperty',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='properties',
        ),
    ]
