# Generated by Django 4.2.3 on 2023-07-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_remove_processinglevel_id_remove_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinglevel',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='new_id',
            new_name='id',
        ),
    ]
