# Generated by Django 4.1 on 2023-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_rename_new_id_processinglevel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(max_length=255),
        ),
    ]
