# Generated by Django 4.1.5 on 2023-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_alter_processinglevel_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedproperty',
            name='variable_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='variable_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='model_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sampling_feature_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sampling_feature_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='site_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thingassociation',
            name='is_primary_owner',
            field=models.BooleanField(default=False),
        ),
    ]
