# Generated by Django 4.1 on 2023-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_alter_observedproperty_variable_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
