# Generated by Django 4.1.4 on 2023-03-02 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_sensor_method_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AddField(
            model_name='location',
            name='elevation_datum',
            field=models.CharField(default='MSL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='elevation_m',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='id'
        ),
        migrations.AddField(
            model_name='datastream',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='location',
            name='thing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='sites.thing'),
        ),
        migrations.RemoveField(
            model_name='observedproperty',
            name='id'
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='observed_property',
        ),
        migrations.AddField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.observedproperty'),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
