# Generated by Django 4.1 on 2023-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_alter_observedproperty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='data_disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
