# Generated by Django 4.1.7 on 2023-03-17 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_alter_observation_options_remove_location_elevation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.FloatField()),
                ('result_time', models.DateTimeField()),
                ('result_quality', models.CharField(max_length=255, null=True)),
                ('phenomenon_time', models.DateTimeField(blank=True, null=True)),
                ('valid_begin_time', models.DateTimeField(blank=True, null=True)),
                ('valid_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
