# Generated by Django 4.1 on 2023-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_thing_data_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='include_data_disclaimer',
            field=models.BooleanField(default=False),
        ),
    ]
