# Generated by Django 4.1 on 2023-03-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='elevation_m',
            new_name='elevation',
        ),
    ]
