# Generated by Django 4.1 on 2023-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_alter_observedproperty_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
