# Generated by Django 4.1 on 2023-05-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_datastream_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.observedproperty'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.processinglevel'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sites.sensor'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.unit'),
        ),
    ]
