# Generated by Django 4.1 on 2023-05-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_alter_datastream_observed_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='county',
        ),
    ]
