# Generated by Django 4.1 on 2023-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_rename_country_location_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
