# Generated by Django 4.1 on 2023-06-26 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0023_thing_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='data_source_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('header_row', models.PositiveIntegerField(blank=True, null=True)),
                ('data_start_row', models.PositiveIntegerField(blank=True, null=True)),
                ('delimiter', models.CharField(blank=True, max_length=1, null=True)),
                ('quote_char', models.CharField(blank=True, max_length=1, null=True)),
                ('interval', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_units', models.CharField(blank=True, max_length=255, null=True)),
                ('crontab', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('paused', models.BooleanField()),
                ('timestamp_column', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_format', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_offset', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_thru', models.DateTimeField(blank=True, null=True)),
                ('last_sync_successful', models.BooleanField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.datasource'),
        ),
    ]
