# Generated by Django 4.1 on 2023-07-10 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0024_datastream_data_source_column_datasource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='owner',
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_loader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.dataloader'),
        ),
        migrations.CreateModel(
            name='DataLoaderOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('data_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.dataloader')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('data_loader', 'person')},
            },
        ),
    ]
