# Generated by Django 4.1 on 2023-07-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_datasourceowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_sync_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
