# Generated by Django 4.1 on 2023-07-13 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0027_datasource_last_sync_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sites.thing')),
            ],
        ),
    ]
