name: HydroServer AWS Elastic Beanstalk Deployment
run-name: ${{ github.actor }} is deploying HydroServer to AWs Elastic Beanstalk on ${{ github.ref }}

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'

      - name: Upload deployment package to S3
        run: aws s3 cp deploy_package.zip s3://ciroh-his/deploy/prod/deploy_package_${{ github.ref_name }}.zip

      - name: Create ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ciroh-his-django \
          --source-bundle S3Bucket="ciroh-his",S3Key="deploy/prod/deploy_package_${{ github.ref_name }}.zip" \
          --version-label "${{ github.ref_name }}" \
          --description "commit-sha-${{ github.sha }}"
          
      - name: Deploy ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ciroh-his-prod-test \
          --version-label "${{ github.ref_name }}"