name: HydroServer Tests
run-name: ${{ github.actor }} is running HydroServer Tests on ${{ github.ref }}

on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: windows-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: 3.10
          activate-environment: his
          environment-file: environment.yml
          use-mamba: true

#         # caching dependency will make our build faster.
#       - name: Cache dependency
#         uses: actions/cache@v2
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       - name: Set Up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install requirements
#         run: |
#           pip install -r requirements.txt

      - name: Run tests
        run: |
            python manage.py test

