name: HydroServer Tests
run-name: ${{ github.actor }} is running HydroServer Tests on ${{ github.ref }}

on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: windows-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          activate-environment: his
          environment-file: environment.yml
          use-mamba: true

      - name: Export environment variable
        run: |
          echo "::set-env name=GOOGLE_MAPS_API_KEY::${{ secrets.GOOGLE_MAPS_API_KEY }}"

      - name: Run tests
        run: |
            python manage.py test
